### ISSUE TITLE
Fix CustomerStateResolver typos

### ISSUE THREAD

**Issue by bigboss86** [BitBagCommerce/SyliusBlacklistPlugin#45]
There are minor typos in that class:

BitBag\SyliusBlacklistPlugin\StateResolver\CustomerStateResolver line 24:
private $productManager;
should be:
private $customerManager;

BitBag\SyliusBlacklistPlugin\StateResolver\CustomerStateResolver line 29:
$this->productManager = $customerManager;
should be:
$this->customerManager = $customerManager;

BitBag\SyliusBlacklistPlugin\StateResolver\CustomerStateResolver lines 43 and 44:
$this->productManager->persist($customer);
$this->productManager->flush();
should be:
$this->customerManager->persist($customer);
$this->customerManager->flush();

Regards!

**Comment by jakubtobiasz** [comment]
Hi 🙋🏻‍♂️!

Thank your for creating the issue! The problem you've described will be resolved after merging #57. 

Once again, thank you 🙏🏻!
