### ISSUE TITLE
Impossible to override FraudSuspicion because of Factory

### ISSUE THREAD

**Issue by Roshyo** [BitBagCommerce/SyliusBlacklistPlugin#47]
**Poblem:**
Due to the fact that in `BitBag\SyliusBlacklistPlugin\Factory\FraudSuspicionFactory` there is `return new FraudSuspicion();` done directly, it is impossible to override FraudSuspicion entity without copying the whole factory too (otherwise we don't have the expected instance in forms ie.)

**Solution:**
`BitBag\SyliusBlacklistPlugin\Factory\FraudSuspicionFactory` should decorate Sylius resource factory, and then start relying on the whole ResourceBundle concept to allow override.

**Comment by kptLucek** [comment]
Hi there,

Thanks for reporting, we'll take look over this one

**Comment by Roshyo** [comment]
Thanks ! :tada:
