### ISSUE TITLE
Repositories should not be decoration but extension

### ISSUE THREAD

**Issue by Roshyo** [BitBagCommerce/SyliusBlacklistPlugin#50]
When customizing Sylius, repositories should be extending the native one, and their configuration should be declared in Resource mapping.

Right now, it is not the case for the FraudSuspicion Repository. It is currently a decoration. And it causes troubles when using the GridBundle (as you can see here: https://sylius-demo.bitbag.io/admin/fraud-suspicions/)

**Comment by jakubtobiasz** [comment]
#55 fixed a bug with Fraud Suspicions index page. I close this issue as the main problem has been fixed. The topic of decorating will be continued in #53 PR.
